### ISSUE TITLE
サイドバーメニューの順番

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-admin-web#17]
以下の順番に修正お願いします、

ダッシュボード
ユーザー
注文管理
換金
問題
違反通告
お知らせ
設定
AirMaidについて
FAQ
利用規約
特定商取引法
プライバシーポリシー

**Comment by take-iwa** [comment]
@alexeypolitov 順番変わってません。確認お願いします。
<img width="197" alt="2017-08-17 22 21 01" src="https://user-images.githubusercontent.com/23730555/29414363-65febc8c-839a-11e7-8c3d-1c7da015984c.png">

**Comment by take-iwa** [comment]
開発環境では、直っています。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
