### ISSUE TITLE
プライバシーポリシー

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-admin-web#18]
文章はこれでお願いします。
[プライバシーポリシー.txt](https://github.com/DecodeLLC/cookle-admin-web/files/1062816/default.txt)

**Comment by alexeypolitov** [comment]
@take-iwa こちらh管理画面でアップしていただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov そうですよね。なんであげたんでしょうか。すみません。閉じます。
