### ISSUE TITLE
通知バッジの表示追加

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-admin-web#21]
新しい情報が追加された時に、サイドバーメニューの文字の横に通知バッジを表示してほしい。

＜通知を表示するメニュー＞
・換金
・問題
・違反報告

**Comment by alexeypolitov** [comment]
@take-iwa いまのところでお知らせは来た順で表示されてます。そこはどう言う問題ですか？詳しく説明していただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 管理者の方で気付きやすく見逃しが無いように・と思って書いたんだと思います。以下のようなのをイメージしてたんですが、いらないですかね？

<img width="237" alt="_2017-07-24_14_07_06" src="https://user-images.githubusercontent.com/23730555/28509047-70e178b6-707a-11e7-8a11-a1995fc4530d.png">

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました
