### ISSUE TITLE
ダッシュボードの表示項目について

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-admin-web#23]
以下の項目をグラフ表示できるようお願いします。

＜日単位＞
・訪問者数
・ユーザー登録数
・サービス登録数
・注文合計数
　└カテゴリ毎の注文数
　└クレジット払い
　└銀行振替
　└現金払い
・換金申請数
・問題報告数
・違反報告数

＜全体集計＞
・ユーザー
　└性別
　　└ サービス登録者割合
　└ 年代別（１０代、２０代・・・）
　　└ サービス登録者割合
・サービス
　└カテゴリ別登録数
　　└サブカテゴリも
　└できれば、配達エリアから都道府県別のサービス数もあれば

**Comment by alexeypolitov** [comment]
@take-iwa 対応できる項目：

＜日単位＞
・訪問者数
・ユーザー登録数
・サービス登録数
・注文合計数
・換金申請数
・問題報告数
・違反報告数

＜全体集計＞
・ユーザー数
・サービス数

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました
