### ISSUE TITLE
有料バナー料金の設定は、どこに反映さているのか？

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/cookle-admin-web#30]
設定の有料バナー料金は、どこに反映されるのか？
<img width="297" alt="_2017-09-08_8_31_40" src="https://user-images.githubusercontent.com/23730555/30189687-700a303a-9470-11e7-958b-544bb18ab532.png">

サービス登録で有料掲載にした場合の料金かと思ったが、それらは以下のような値段になっている。
<img width="131" alt="_2017-09-08_8_34_21" src="https://user-images.githubusercontent.com/23730555/30189718-9f7dbb52-9470-11e7-8a72-119ea4cbcf67.png">
<img width="127" alt="_2017-09-08_8_34_27" src="https://user-images.githubusercontent.com/23730555/30189724-a5ae2d18-9470-11e7-9c04-99f2860d0636.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
